### ISSUE TITLE
Placeholder and text will overlap when set text using code.

### ISSUE THREAD

**Issue by yatindra99jain** [GurinderBatth/GBFloatingTextField#1]
Placeholder and text will overlap when set text using code. Please find attached screenshot.
It will be fine when i edit some text from text field. It is showing error white set text programmatically.

![Simulator Screen Shot - iPhone X - 2019-03-09 at 22 35 12](https://user-images.githubusercontent.com/7301965/54074696-a9681900-42bb-11e9-82a9-349da9c06266.png)

**Comment by GurinderBatth** [comment]
I resolved this issue in new version. Thanks for your feedback. Sorry for delay.

**Comment by hiteshborse12** [comment]
For quick fix:
Call textFieldDidChange method 😄 : 
eg: 
        self.nameTextField.text = "new text"
        self.nameTextField.textFieldDidChange(self.emailTextField)
